#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Org     = $env:ADO_ORG
$Project = $env:ADO_PROJECT
if (-not $Org)     { Write-Error "ADO_ORG not set"; exit 1 }
if (-not $Project) { Write-Error "ADO_PROJECT not set"; exit 1 }

$baseUrl     = "https://dev.azure.com/$Org/$([Uri]::EscapeDataString($Project))"
$priorityMap = @{ Critical = 1; High = 2; Medium = 3; Low = 4 }

Write-Host "Authenticating with Azure..."
$token = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query accessToken -o tsv
if (-not $token) { Write-Error "az login required"; exit 1 }
$headers = @{ Authorization = "Bearer $token" }

function Update-WorkItem {
    param(
        [int]$Id,
        [string]$Title,
        [string]$Description,
        [string]$AcceptanceCriteria = "",
        [int]$StoryPoints,
        [string]$Priority,
        [string]$Tags = ""
    )
    $ops = [System.Collections.Generic.List[hashtable]]::new()
    $ops.Add(@{ op = "add"; path = "/fields/System.Title";                      value = $Title })
    $ops.Add(@{ op = "add"; path = "/fields/System.Description";                value = $Description })
    $ops.Add(@{ op = "add"; path = "/multilineFieldsFormat/System.Description"; value = "Markdown" })
    if ($AcceptanceCriteria) {
        $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Common.AcceptanceCriteria";                value = $AcceptanceCriteria })
        $ops.Add(@{ op = "add"; path = "/multilineFieldsFormat/Microsoft.VSTS.Common.AcceptanceCriteria"; value = "Markdown" })
    }
    $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Scheduling.StoryPoints"; value = $StoryPoints })
    $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Common.Priority";        value = $priorityMap[$Priority] })
    if ($Tags) {
        $ops.Add(@{ op = "add"; path = "/fields/System.Tags"; value = $Tags })
    }
    $url  = "$baseUrl/_apis/wit/workItems/$Id`?api-version=7.1"
    $body = $ops | ConvertTo-Json -Depth 6
    Write-Host "  AB#$Id  $Title"
    Invoke-RestMethod -Method Patch -Uri $url -Headers $headers -Body $body -ContentType "application/json-patch+json" | Out-Null
    Write-Host "    -> Updated"
}

# Update-WorkItem calls go here — generated by the push-to-ado skill.
