#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Org     = $env:ADO_ORG
$Project = $env:ADO_PROJECT
if (-not $Org)     { Write-Error "ADO_ORG not set"; exit 1 }
if (-not $Project) { Write-Error "ADO_PROJECT not set"; exit 1 }

$baseUrl     = "https://dev.azure.com/$Org/$([Uri]::EscapeDataString($Project))"
$priorityMap = @{ Critical = 1; High = 2; Medium = 3; Low = 4 }

Write-Host "Authenticating with Azure..."
$token = az account get-access-token --resource 499b84ac-1321-427f-aa17-267ca6975798 --query accessToken -o tsv
if (-not $token) { Write-Error "az login required"; exit 1 }
$headers = @{ Authorization = "Bearer $token" }

function New-WorkItem {
    param(
        [string]$Type,
        [string]$Title,
        [string]$Description,
        [string]$AcceptanceCriteria = "",
        [int]$StoryPoints = 0,
        [string]$Priority = "Medium",
        [int]$ParentId = 0,
        [string]$Tags = ""
    )

    $ops = [System.Collections.Generic.List[hashtable]]::new()
    $ops.Add(@{ op = "add"; path = "/fields/System.Title";                      value = $Title })
    $ops.Add(@{ op = "add"; path = "/fields/System.Description";                value = $Description })
    $ops.Add(@{ op = "add"; path = "/multilineFieldsFormat/System.Description"; value = "Markdown" })
    $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Common.Priority";    value = $priorityMap[$Priority] })

    if ($AcceptanceCriteria) {
        $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Common.AcceptanceCriteria";                        value = $AcceptanceCriteria })
        $ops.Add(@{ op = "add"; path = "/multilineFieldsFormat/Microsoft.VSTS.Common.AcceptanceCriteria";         value = "Markdown" })
    }
    if ($StoryPoints -gt 0) {
        $ops.Add(@{ op = "add"; path = "/fields/Microsoft.VSTS.Scheduling.StoryPoints"; value = $StoryPoints })
    }
    if ($Tags) {
        $ops.Add(@{ op = "add"; path = "/fields/System.Tags"; value = $Tags })
    }
    if ($ParentId -gt 0) {
        $ops.Add(@{
            op    = "add"
            path  = "/relations/-"
            value = @{
                rel        = "System.LinkTypes.Hierarchy-Reverse"
                url        = "$baseUrl/_apis/wit/workItems/$ParentId"
                attributes = @{ comment = "" }
            }
        })
    }

    $encodedType = [Uri]::EscapeDataString($Type)
    $url         = "$baseUrl/_apis/wit/workItems/`$$encodedType`?api-version=7.1"
    $body        = $ops | ConvertTo-Json -Depth 6

    Write-Host "  [$Type] $Title"
    $r   = Invoke-RestMethod -Method Patch -Uri $url -Headers $headers -Body $body -ContentType "application/json-patch+json"
    $id  = $r.id
    Write-Host "    -> AB#$id  $baseUrl/_workitems/edit/$id"
    return $id
}

# Work item definitions go here — generated by the push-to-ado skill.
